sudo: false
language: perl
perl:
   - '5.22'
   - '5.20'
   - '5.18'
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - dzil authordeps --missing | cpanm
   - dzil listdeps --author --missing | cpanm
script:
   - dzil test --release --author
