sudo: false
language: perl
perl:
   - '5.22'
   - '5.20'
   - '5.18'
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - dzil authordeps  --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest
   - dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose
script:
   - dzil test --release --author
